apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-sqcxddad
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-sqcxddad 
  name: go-sqcxddad
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-sqcxddad
    weight: 100 
